# Generated by Django 5.0.2 on 2024-02-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(verbose_name='Etapa')),
                ('aplication_date', models.DateField(verbose_name='Fecha de la aplicación')),
            ],
        ),
    ]
